spring:
  application:
    name: marine-management-service
  datasource:
    url: jdbc:mysql://localhost:3307/marine_management_db
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
#  security:
#    user:
#      name: admin
#      password: admin-password
  sql:
    init:
      mode: always
server:
  port: 8080